version: "3.4"

services:

  #
  # MongoDB is used to store the shortend URLs
  # see https://hub.docker.com/_/mongo/
  # and https://www.mongodb.com
  #
  mongo:
    image: mongo:latest
    restart: unless-stopped

    volumes:
    - gmeshort-mongo-data:/data/db

  #
  # Redis is used for temporary stats
  # and for pub-sub use (caching)
  # see https://hub.docker.com/_/redis/
  # and https://redis.io
  #
  redis:
    image: redis:latest
    restart: unless-stopped

  #
  # Main app
  # see https://github.com/full-stack-gods/GMEshortener
  #
  gmeshort:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - 1333:1336
    environment:
      # MongoDB
      MONGODB_APPLYURI: "mongodb://mongo:27017"
      # Redis
      REDIS_USE: "true"
      REDIS_ADDR: "redis:6379"
      REDIS_DB: "0"

volumes:
  gmeshort-mongo-data: