version: "3.4"

services:

  #
  # MongoDB is used to store the shortend URLs
  # see https://hub.docker.com/_/mongo/
  # and https://www.mongodb.com
  #
  mongo:
    image: mongo:latest
    restart: unless-stopped

    volumes:
    - gmeshort-mongo-data:/data/db

  #
  # Redis is used for temporary stats
  # and for pub-sub use (caching)
  # see https://hub.docker.com/_/redis/
  # and https://redis.io
  #
  redis:
    image: redis:latest
    restart: unless-stopped

  #
  # Main app
  # see https://github.com/gme-sh/gme.sh-api
  #
  gmeshort:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
    ports:
      - 1334:80
    environment:
      GME_PERSISTENT_BACKEND: "Mongo"
      GME_STATS_BACKEND: "Redis"
      GME_PUBSUB_BACKEND: "Redis"
      GME_CACHE_BACKEND: "Local"
      GME_WEB_ADDR: "0.0.0.0:80"
      GME_MDB_APPLY_URI: "mongodb://mongo:27017"
      GME_REDIS_ADDR: "redis:6379"

volumes:
  gmeshort-mongo-data: